spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calorie_diary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.mail.ru
    port: 465
    username:
    password:
    from:
    protocol: smtps
    smtps:
      auth: true
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
